# Generated by Django 4.2.7 on 2023-12-22 05:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LearnIt', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videos',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='notes',
            unique_together={('customer', 'module')},
        ),
        migrations.RemoveField(
            model_name='notes',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='stage',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
