# Generated by Django 4.2.6 on 2024-05-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnIt', '0002_videos_sub_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='sub_module',
        ),
    ]
