# Generated by Django 3.2.4 on 2021-06-25 09:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LearnIt', '0003_notes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notes',
            unique_together={('customer', 'stage', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='videos',
            unique_together={('stage', 'module')},
        ),
    ]
