# Generated by Django 3.2.4 on 2021-06-25 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnIt', '0004_auto_20210625_1511'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videos',
            unique_together=set(),
        ),
    ]
