# Generated by Django 3.2.4 on 2021-06-25 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearnIt', '0005_alter_videos_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='videos',
            unique_together={('stage', 'module')},
        ),
    ]
