# Generated by Django 3.2.4 on 2021-07-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnIt', '0006_alter_videos_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='faq',
            field=models.TextField(blank=True, null=True),
        ),
    ]
