# Generated by Django 3.2.4 on 2021-07-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnIt', '0007_videos_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='relatedPost',
            field=models.TextField(blank=True, null=True),
        ),
    ]
