# Generated by Django 3.2.4 on 2021-09-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnIt', '0008_videos_relatedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
