# Generated by Django 3.2.4 on 2021-09-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnIt', '0009_alter_modules_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modules',
            options={'verbose_name': 'Learnit module'},
        ),
        migrations.AlterField(
            model_name='stage',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
