# Generated by Django 4.2.6 on 2023-11-21 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicinetime',
            options={'verbose_name': 'Medicine time(manual)'},
        ),
    ]
