# Generated by Django 4.2.6 on 2023-11-23 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0003_takenmedicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreastfeedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feeding_number', models.PositiveSmallIntegerField()),
                ('is_breastfed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breastfeeding_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
