# Generated by Django 4.2.7 on 2023-12-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_customexercises'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomExercises',
        ),
    ]
