# Generated by Django 4.2.6 on 2023-11-24 07:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0004_breastfeedingrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='breastfeedingrecord',
            unique_together={('user', 'date', 'feeding_number')},
        ),
    ]
