# Generated by Django 4.2.6 on 2023-11-24 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0005_alter_breastfeedingrecord_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='breastfeedingrecord',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='breastfeedingrecord',
            name='feeding_number',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='UserBreastfeedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('breastfeeding_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_records', to='Customer.breastfeedingrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='breastfeedingrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='breastfeedingrecord',
            name='user',
        ),
    ]
