# Generated by Django 4.2.6 on 2023-11-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_alter_breastfeedingrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breastfeedingrecord',
            name='feeding_number',
            field=models.CharField(),
        ),
    ]
