# Generated by Django 4.2.7 on 2023-12-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_exercises_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='user',
        ),
        migrations.DeleteModel(
            name='CompletedExercises',
        ),
        migrations.DeleteModel(
            name='Exercises',
        ),
    ]
