# Generated by Django 4.2.6 on 2023-11-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_alter_breastfeedingrecord_feeding_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbreastfeedingrecord',
            name='is_breastfed',
            field=models.BooleanField(default=False),
        ),
    ]
