# Generated by Django 4.2.6 on 2023-11-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_userbreastfeedingrecord_is_breastfed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbreastfeedingrecord',
            name='breastfeeding_record',
        ),
        migrations.RemoveField(
            model_name='userbreastfeedingrecord',
            name='user',
        ),
        migrations.DeleteModel(
            name='BreastfeedingRecord',
        ),
        migrations.DeleteModel(
            name='UserBreastfeedingRecord',
        ),
    ]
