# Generated by Django 4.2.7 on 2023-12-05 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_exercisevideos_exercises_customexercises_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='stage',
        ),
    ]
