# Generated by Django 4.2.7 on 2023-12-05 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_remove_exercises_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedexercises',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='completedexercises',
            name='exercise',
        ),
        migrations.AlterUniqueTogether(
            name='customexercises',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='customexercises',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='exercisevideos',
            name='stage',
        ),
        migrations.DeleteModel(
            name='CompletedCustomeExercises',
        ),
        migrations.DeleteModel(
            name='CompletedExercises',
        ),
        migrations.DeleteModel(
            name='CustomExercises',
        ),
        migrations.DeleteModel(
            name='Exercises',
        ),
        migrations.DeleteModel(
            name='ExerciseVideos',
        ),
    ]
