# Generated by Django 4.2.6 on 2023-11-24 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0009_remove_userbreastfeedingrecord_breastfeeding_record_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreastfeedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeding_number', models.CharField()),
                ('is_breastfed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserBreastfeedingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_breastfed', models.BooleanField(default=False)),
                ('breastfeeding_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_records', to='Customer.breastfeedingrecord')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
