# Generated by Django 4.2.6 on 2023-11-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_breastfeedingrecord_userbreastfeedingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbreastfeedingrecord',
            name='feeding_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
