# Generated by Django 4.2.6 on 2023-11-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_userbreastfeedingrecord_feeding_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breastfeedingrecord',
            name='feeding_number',
            field=models.CharField(max_length=50),
        ),
    ]
