# Generated by Django 4.2.7 on 2023-12-07 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0011_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Meal (Manual)',
            },
        ),
        migrations.CreateModel(
            name='DietTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('food', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=0, null=True)),
                ('calorie', models.PositiveIntegerField(default=0, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.meal')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('customer', 'date', 'meal')},
            },
        ),
    ]
