# Generated by Django 4.2.7 on 2023-12-18 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Customer', '0013_vaccinations_vaccination_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination_user',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Brain_visual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('ans', models.CharField(max_length=29)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Brain_sense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sense', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=10)),
                ('question', models.CharField(max_length=20)),
                ('ans', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
