# Generated by Django 4.2.7 on 2023-12-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0015_brain_sense_user_remove_brain_sense_ans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brain_sense_user',
            name='ans',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
