# Generated by Django 4.2.7 on 2023-12-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0016_brain_sense_user_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brain_sense_user',
            name='ans',
            field=models.BooleanField(default=False),
        ),
    ]
