# Generated by Django 4.2.7 on 2023-12-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0018_diapering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diapering',
            name='wet',
            field=models.BooleanField(default=True),
        ),
    ]
