# Generated by Django 4.2.6 on 2023-10-16 20:21

import Accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPostNatal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default='example@email.com', max_length=300, unique=True)),
                ('firstname', models.CharField(default='firstname', max_length=100, validators=[Accounts.validators.CheckIfAlpha])),
                ('lastname', models.CharField(max_length=100, null=True, validators=[Accounts.validators.CheckIfAlpha])),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('babydob', models.DateField(null=True)),
                ('babyGender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('profile_img', models.ImageField(blank=True, default='/ProfilePic/default.jpg', null=True, upload_to='ProfilePic/')),
                ('is_active', models.BooleanField(default=True)),
                ('dateJoined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
    ]
