# Generated by Django 4.2.6 on 2023-11-02 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('DOCTOR', 'Doctor'), ('SALES', 'Sales'), ('ADMIN', 'Admin')], default='client', max_length=10),
        ),
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=200, null=True)),
                ('qualification', models.CharField(max_length=200, null=True)),
                ('medicalCouncil', models.CharField(max_length=20, null=True)),
                ('councilRegNo', models.CharField(max_length=200, null=True)),
                ('hospitals', models.CharField(max_length=300, null=True)),
                ('interests', models.CharField(max_length=200, null=True)),
                ('placeOfWork', models.CharField(max_length=200, null=True)),
                ('onlineConsultation', models.CharField(max_length=100, null=True)),
                ('experience', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('languages', models.CharField(default='', max_length=500)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('referalId', models.CharField(max_length=100, null=True, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male')], max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docDetails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
