# Generated by Django 4.2.7 on 2023-12-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, default='/ProfilePic/default.jpg', null=True, upload_to='ProfilePic/'),
        ),
    ]
