# Generated by Django 4.2.6 on 2023-11-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_user_role_doctordetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('DOCTOR', 'Doctor'), ('SALES', 'Sales'), ('ADMIN', 'Admin')], default='CLIENT', max_length=10),
        ),
    ]
