# Generated by Django 4.2.6 on 2023-10-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_userpostnatal_role_customerdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetails',
            old_name='date_of_birth',
            new_name='date_of_birth_parent',
        ),
        migrations.RemoveField(
            model_name='customerdetails',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userpostnatal',
            name='babyGender',
        ),
        migrations.RemoveField(
            model_name='userpostnatal',
            name='babydob',
        ),
        migrations.RemoveField(
            model_name='userpostnatal',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='babyGender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='babydob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customerdetails',
            name='profile_img',
            field=models.ImageField(blank=True, default='/ProfilePic/default.jpg', null=True, upload_to='ProfilePic/'),
        ),
    ]
