# Generated by Django 4.2.6 on 2023-11-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_consultantinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('DOCTOR', 'Doctor'), ('SALES', 'Sales'), ('ADMIN', 'Admin'), ('CONSULTANT', 'Consultant')], default='CLIENT', max_length=10),
        ),
    ]
