# Generated by Django 4.2.6 on 2023-11-08 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='doctor_referal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.doctordetails'),
        ),
    ]
