# Generated by Django 4.2.6 on 2023-11-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_customerdetails_doctor_referal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Doctor'), (3, 'Client'), (4, 'Sales'), (5, 'Consultant')], default=3),
        ),
    ]
