# Generated by Django 3.2.4 on 2023-08-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='ist_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
