# Generated by Django 5.0.2 on 2024-04-28 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallResponses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'CallResponses (Manual)',
            },
        ),
        migrations.CreateModel(
            name='CustomerCallReposnses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sales.callresponses')),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.salesteamdetails')),
            ],
            options={
                'unique_together': {('customer', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PatientDetailsApporval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.customerdetails')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.doctordetails')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('doctor', 'customer')},
            },
        ),
    ]
